# Use Node.js 18
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY . .

# Install dependencies
RUN npm install

# Copy the rest of your application's source code
COPY . .

# Expose the frontend port
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]