version: "3.8"

services:
  backend:
    build:
      context: ./social-media-backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "5001:4444"
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: LordStarkWinter
      DATABASE_NAME: nestdb
      PORT: 4444
    networks:
      - app-network

  frontend:
    build:
      context: ./social-media-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: LordStarkWinter
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
